### ISSUE TITLE
If this project can build Android and iOS package and deploy Live update on Ionic Dashboard ?

### ISSUE THREAD

**Issue by vfmlucasguo** [ionic-team/cs-portals-capacitor-ng#5]
Hi ,
I have successfully run the project locally： [https://github.com/ionic-team/cs-portals-capacitor-ng](https://github.com/ionic-team/ionic-portals/issues/url)，but there were problems

When I run: npm run run:all，The shell wasn't running, so I need to run : nx run shell:serve -o

![image](https://user-images.githubusercontent.com/97436761/198421723-a5268f73-294a-49e6-9aa8-cfeb35c99009.png)

When I want to build the Demo in ionic dashboard it failed，I wonder if this supports live update，Can it be packaged with Android and iOS in ionic dashboard ？
![image](https://user-images.githubusercontent.com/97436761/198421749-bec0c9a5-4ba5-4214-81ca-4c54a5167ef5.png)

thanks !

**Comment by Steven0351** [comment]
Hey @vfmlucasguo, sorry for the delay. You need a key for Portals for Capacitor, which you can get a trial for by filling [this form](https://go.ionicframework.com/portals-for-capacitor). Once you've gotten the trial, you'll need to follow [these steps](https://ionic.io/docs/supported-plugins/setup) to be able to pull in the `@ionic-enterprise/capacitor-portals` package
